#!/bin/sh

git_fuzzy_log() {
  # shellcheck disable=SC2016
  PREVIEW_COMMAND='f() {
    set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}")
    [ $# -eq 0 ] || git show --color=always $1 | delta 
  }; f {}'

  ENTER_COMMAND='(grep -o "[a-f0-9]\{7\}" | head -1 |
    xargs -I % sh -c "git show --color=always % | delta") << "FZF-EOF"
    {}
    FZF-EOF'

  # shellcheck disable=SC2086
  # shellcheck disable=SC2068
  git log --graph --color=always \
    --format='%C(auto)%h %an %C(blue)%s %C(magenta)%cr' $@ \
    | fzf --height=100% --no-sort --tiebreak=index --exit-0 \
      --preview "${PREVIEW_COMMAND}" --bind "enter:execute:${ENTER_COMMAND}"
}

git_fuzzy_log "@"
