git_protocol: ssh
prompt: enabled
glamour_style: dark
editor:
pager:
aliases:
  co: pr checkout
  repos: |
    !gh api --paginate graphql -f owner="$1" -f query='
      query($owner: String!, $per_page: Int = 100, $endCursor: String) {
        repositoryOwner(login: $owner) {
          repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
            nodes { nameWithOwner }
            pageInfo { hasNextPage endCursor }
          }
        }
      }
    ' | jq -r '.data.repositoryOwner.repositories.nodes[].nameWithOwner' | sort
