editor:
git_protocol: ssh
glamour_style: dark
pager:
prompt: enabled
aliases:
  diff: pr diff
  mine: pr list --author @me
  review: |
    !gh pr list \
    | fzf --ansi --height '100%' --preview 'gh pr view {1}' --header-lines 3 \
    | awk '{print $1}' \
    | xargs -I {} sh -c 'gh pr checkout "$1" && nvim -c ":Octo pr edit ${1#"#"}"' -- {} 2> /dev/null || true
  repos: |
    !gh api --paginate graphql -f owner="$1" -f query='
      query($owner: String!, $per_page: Int = 100, $endCursor: String) {
        repositoryOwner(login: $owner) {
          repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
            nodes { nameWithOwner }
            pageInfo { hasNextPage endCursor }
          }
        }
      }
    ' --jq '.data.repositoryOwner.repositories.nodes[].nameWithOwner' | sort
version: "1"
