editor:
git_protocol: ssh
glamour_style: dark
pager:
prompt: enabled
aliases:
  diff: pr diff
  mine: pr list --author @me
  review: |
    !zsh -ci fzf-gh-pr-widget
  repos: |
    !gh api --paginate graphql -f owner="$1" -f query='
      query($owner: String!, $per_page: Int = 100, $endCursor: String) {
        repositoryOwner(login: $owner) {
          repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
            nodes { nameWithOwner }
            pageInfo { hasNextPage endCursor }
          }
        }
      }
    ' --jq '.data.repositoryOwner.repositories.nodes[].nameWithOwner' | sort
version: "1"
