local M = {}

---@param c util.theme.palette
---@return util.theme.hl
function M.get(c)
  -- stylua: ignore
  return {
    -- treesitter highlighting
    ["@annotation"]                   = { link = "PreProc" },
    ["@attribute"]                    = { link = "PreProc" },

    ["@character.printf"]             = { link = "SpecialChar" },
    ["@character.special"]            = { link = "SpecialChar" },
    ["@class"]                        = { fg = c.aqua2, bold = true },
    ["@comment"]                      = { link = "Comment" },
    ["@comment.documentation"]        = { link = "SpecialComment" },
    ["@comment.error"]                = { fg = c.red2 },
    ["@comment.hint"]                 = { fg = c.cyan1 },
    ["@comment.info"]                 = { fg = c.aqua0 },
    ["@comment.note"]                 = { fg = c.cyan1 },
    ["@comment.todo"]                 = { fg = c.blue3 },
    ["@comment.warning"]              = { fg = c.yellow1 },
    ["@constant.builtin"]             = { link = "Special" },
    ["@constant.macro"]               = { link = "Define" },
    ["@constructor"]                  = { fg = c.purple1 },
    ["@constructor.tsx"]              = { fg = c.aqua1 },
    ["@definition.enum"]              = { bold = true },
    ["@function.builtin"]             = { link = "Special" },
    ["@function.call"]                = { link = "@function" },
    ["@function.macro"]               = { link = "Macro" },
    ["@function.method"]              = { link = "Function" },
    ["@function.method.call"]         = { link = "@function.method" },
    ["@keyword.coroutine"]            = { link = "@keyword" },
    ["@keyword.function"]             = { fg = c.purple1 },
    ["@keyword.operator"]             = { link = "@operator" },
    ["@keyword.return"]               = { link = "@keyword" },
    ["@label"]                        = { fg = c.blue3 },
    ["@markup"]                       = { link = "@none" },
    ["@markup.danger"]                = { fg = c.bg2, bg = c.red2 },
    ["@markup.diff.add"]              = { link = "DiffAdd" },
    ["@markup.diff.delete"]           = { link = "DiffDelete" },
    ["@markup.emphasis"]              = { italic = true },
    ["@markup.link"]                  = { fg = c.cyan1 },
    ["@markup.list"]                  = { fg = c.aqua1 },
    ["@markup.list.checked"]          = { fg = c.cyan1 },
    ["@markup.list.markdown"]         = { fg = c.orange2, bold = true },
    ["@markup.list.unchecked"]        = { fg = c.blue3 },
    ["@markup.note"]                  = { fg = c.bg2, bg = c.aqua0 },
    ["@markup.raw.markdown_inline"]   = { bg = c.bg2, fg = c.blue3 },
    ["@module"]                       = { link = "Include" },
    ["@module.builtin"]               = { fg = c.red3 },
    ["@operator"]                     = { fg = c.aqua3 },
    ["@property"]                     = { fg = c.cyan1 },
    ["@punctuation.bracket"]          = { fg = c.fg1 },
    ["@punctuation.delimiter"]        = { fg = c.aqua3 },
    ["@punctuation.special"]          = { fg = c.aqua1 },
    ["@punctuation.special.markdown"] = { fg = c.orange2 },
    ["@string.documentation"]         = { fg = c.yellow1 },
    ["@string.escape"]                = { fg = c.purple1 },
    ["@string.regexp"]                = { fg = c.aqua1 },
    ["@tag.attribute"]                = { link = "@property" },
    ["@tag.delimiter.tsx"]            = { fg = ds.color.blend(c.blue3, "#000000", 0.7) },
    ["@tag.tsx"]                      = { fg = c.red3 },
    ["@tag.javascript"]               = { fg = c.red3 },
    ["@type.builtin"]                 = { fg = ds.color.blend(c.aqua1, "#000000", 0.8) },
    ["@variable"]                     = { fg = c.red3 },
    ["@variable.builtin"]             = { fg = c.red3 },
    ["@variable.member"]              = { fg = c.cyan1 },
    ["@variable.parameter"]           = { fg = c.yellow1 },
    ["@variable.parameter.builtin"]   = { fg = ds.color.blend(c.yellow1, "#ffffff", 0.8) },
    ["@variable.parameter.reference"] = { fg = c.rose1 },
  }
end

return M
