"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin Manager
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" install missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
	  \| PlugInstall --sync | source $MYVIMRC
	  \| endif

" define plugin installation directory
call plug#begin('~/.config/vim/remote')

" show completion entries for typed characters
Plug 'vim-scripts/AutoComplPop', { 'on': [] }

" command line fuzzy finder
Plug 'junegunn/fzf.vim', { 'on': ['Files', 'Buffers', 'Ag', 'Rg', 'Windows'] }

" distraction-free writing
Plug 'junegunn/goyo.vim'

" hyperfocus-writing
Plug 'junegunn/limelight.vim'

" emphasize the current matched search pattern
Plug 'wincent/loupe'

" color highlighter
if has('nvim')
  Plug 'norcalli/nvim-colorizer.lua'
endif

" preview/browse json files with ease
if has('nvim')
  Plug 'gennaro-tedesco/nvim-jqx'
endif

" easily identify nested parentheses
Plug 'junegunn/rainbow_parentheses.vim'

" undo history visualizer
Plug 'mbbill/undotree', { 'on': 'UndotreeToggle' }

" file-type aware comments
Plug 'tpope/vim-commentary'

" create file and parent direcory at the same time
Plug 'duggiefresh/vim-easydir'

" a git wrapper for vim
Plug 'tpope/vim-fugitive'

" highlight the yanked region
if !exists('##TextYankPost')
  Plug 'machakann/vim-highlightedyank'
else
  Plug 'machakann/vim-highlightedyank', { 'on': [] }
endif

" highlight sets of matching text
Plug 'andymass/vim-matchup'

" enable repeating supported plug maps with <.>
Plug 'tpope/vim-repeat'

" display git changes in gutter
Plug 'mhinz/vim-signify'

" start screen
Plug 'mhinz/vim-startify'

" surround sequence with tags
Plug 'tpope/vim-surround'

" enable focus events
Plug 'tmux-plugins/vim-tmux-focus-events'

" LSP/VScode snippett supoport
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'

" language snippets
Plug 'cstrap/python-snippets'

" neovim specific plugins
if has('nvim')
  " syntax highlighting for portage
  if isdirectory("/etc/portage")
    Plug 'gentoo/gentoo-syntax'
  endif

  " library that extends core features
  Plug 'nvim-lua/plenary.nvim'
  " framework for setting up language servers
  Plug 'neovim/nvim-lspconfig'
  " auto completion framework
  Plug 'nvim-lua/completion-nvim'
  " centralize installation of lua-language-server (sumneko)
  Plug 'tjdevries/nlua.nvim'
  " extension for completion menu
  Plug 'tjdevries/complextras.nvim'

  " extends quickfix window functionality
  Plug 'RishabhRD/popfix'
  " better defaults for builtin-lsp actions
  Plug 'RishabhRD/nvim-lsputils'

  " parser generator tool
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

  " popup API implementation (WIP)
  Plug 'nvim-lua/popup.nvim'
  " modular fuzzy finder
  Plug 'nvim-telescope/telescope.nvim'
  " pre-compiled fzy sorter
  Plug 'nvim-telescope/telescope-fzy-native.nvim'
endif

call plug#end()
