[note]

language = "en"
default-title = "quick thought"
filename = "{{date now 'timestamp'}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 8
id-case = "lower"

[extra]
author = "Demaro Stanberry"

[group.meetings]
paths = ["_inbox"]
[group.meetings.note]
filename = "{{title}}"
extension = "md"
template = "meeting.md"

[group.wiki]
paths = ["literature"]
[group.wiki.note]
filename = "{{title}}"
extension = "md"
template = "wiki.md"

[format.markdown]
hashtags = true
colon-tags = true
link-format = "wiki"
link-encode-path = false
link-drop-extension = true

[tool]
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "zk list --quiet --format full --limit 1 {-1}"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
