[note]
language = "en"
default-title = "Untitled"
filename = "{{date now '%Y-%m-%d'}}-{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "hex"
id-length = 5
id-case = "lower"

[extra]
author = "Demaro Stanberry"

[group.journal]
paths = ["inbox", "journal"]
[group.journal.note]
filename = "{{date now '%Y-%m-%d'}}-{{id}}"
extension = "md"
template = "journal.md"

[format.markdown]
hashtags = true
colon-tags = true
# link-format = "wiki"
link-format = "[[{{filename}}]]"
link-encode-path = false
link-drop-extension = true

[tool]
editor = "nvim"
pager = "less -iFMRSX"
fzf-preview = "bat -p --color always {-1}"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[lsp.completion]
note-label = "{{title-or-path}}"
note-filter-text = "{{title}} {{path}}"
note-detail = "{{filename-stem}}"
