[note]
language = "en"
default-title = "scratchpad"
filename = "{{date now}}-{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 6
id-case = "lower"

[extra]
author = "Demaro Stanberry"

[group.journal]
paths = ["vault/inbox", "vault/journal"]
[group.journal.note]
filename = "{{date now 'timestamp'}}-{{slug title}}"
extension = "md"
template = "journal.md"

[format.markdown]
hashtags = true
colon-tags = true
link-format = "wiki"
link-encode-path = false
link-drop-extension = true

[tool]
editor = "nvim"
pager = "less -iFMRSX"
fzf-preview = "bat -p --color always {-1}"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[lsp.completion]
note-label = "{{title-or-path}}"
note-filter-text = "{{title}} {{path}}"
note-detail = "{{filename-stem}}"
