###############################################################
# Library
###############################################################
directory: /mnt/d/Music/Desktop

library: /mnt/d/Music/_data/library.db

import:
    copy: no
    move: yes
    write: yes

    autotag: yes
    timid: no

    resume: ask

    default_action: apply
    quiet: no
    quiet_fallback: skip

    singletons: no

clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

ignore: [".*", "*~", "System Volume Information"]

###############################################################
# Path
###############################################################
paths:

    default: %asciify{$albumartist}/%asciify{$album}%aunique{}/$track %asciify{$title}
    singleton: Non-Album/%asciify{$artist}/%asciify{$title}
    comp: Compilations/%asciify{$album}%aunique{}/$track %asciify{$title}

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

path_sep_replace: _

art_filename: cover

max_filename_length: 0

###############################################################
# General
###############################################################
threaded: yes

timeout: 5.0

verbose: no

###############################################################
# UI
###############################################################
list_format_item: %upper{$artist} - $album - $track. $title

list_format_album: %upper{$albumartist} - $album

time_format: '%d-%m-%Y %H:%M:%S'

terminal_encoding: utf8

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

    length_diff_thresh: 10.0
    terminal_width: 80

###############################################################
# Tagging
###############################################################
match:
    strong_rec_thresh: 0.1
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25

    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium

    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0

    preferred:
        countries: ["US"]
        media: []
        original_year: no

    ignored: []
    track_length_grace: 10
    track_length_max: 30

###############################################################
# Plugin List
###############################################################
plugins: [
    convert,
    discogs,
    duplicates,
    embedart,
    fetchart,
    info,
    lyrics,
    lastgenre,
    missing,
    scrub
]

pluginpath: []

###############################################################
# Plugin Config
###############################################################
convert:
    auto: no

    copy_album_art: yes
    never_convert_lossy_files: no

    dest: /mnt/d/Music/Mobile

    max_bitrate: 320

    format: mp3
    formats:
        mp3:
            command: ffmpeg -i $source -ab 320k -map_metadata 0 $dest
            extension: mp3

duplicates:
    checksum: no

embedart:
    auto: yes
    maxwidth: 300

fetchart:
    auto: yes
    cautious: true
    cover_names: albumart art cover folder
    maxwidth: 300

lastgenre:
    auto: yes
    canoncical: yes
    fallback: ''
    source: album
    whitelist: yes

lyrics:
    auto: yes
    fallback: ''

missing:
    count: no
    format: $albumartist - $album - $track - $title
    total: no

replaygain:
    auto: yes
    albumgain: yes
    backend: gstreamer
    overwrite: yes

scrub:
    auto: yes
