gui:
  border: "rounded"
  language: "en"
  mouseEvents: true
  nerdFontsVersion: "3"
  scrollHeight: 2
  scrollPastBottom: true
  showBottomLine: false
  showCommandLog: true
  theme:
    defaultFgColor:
      - default
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - "#59595e"
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#48525e"
