local dap = require "remote.dap"
local map = require "util.map"

map.nnoremap("<c-s-b>", function()
  dap.toggle_breakpoint()
end)
map.nnoremap("<c-s-h>", function()
  dap.widgets.hover()
end)
map.nnoremap("<f3>", function()
  dap.disconnect()
  dap.close()
end)
map.nnoremap("<f5>", function()
  dap.continue()
end)
map.nnoremap("<f6>", function()
  dap.step_into()
end)
map.nnoremap("<f7>", function()
  dap.step_out()
end)
map.nnoremap("<f10>", function()
  dap.step_over()
end)
map.nnoremap("<f12>", function()
  dap.repl.toggle { height = 15 }
end)
