return {
  -- language servers
  "angular-language-server",
  "basedpyright",
  "bash-language-server",
  "clangd",
  "cmake-language-server",
  "copilot-language-server",
  "css-lsp",
  "docker-compose-language-service",
  "dockerfile-language-server",
  "emmet-language-server",
  "eslint-lsp",
  "gh-actions-language-server",
  "gopls",
  "graphql-language-service-cli",
  "helm-ls",
  "html-lsp",
  "json-lsp",
  "lua-language-server",
  "marksman",
  "npm-groovy-lint",
  "powershell-editor-services",
  "pylance",
  "roslyn",
  "ruff",
  "rust-analyzer",
  "snyk-ls",
  "tailwindcss-language-server",
  "terraform-ls",
  "typescript-language-server",
  "vtsls",
  "yaml-language-server",
  (not ds.has "win32" and "zk" or nil),
  -- debuggers
  "codelldb",
  "debugpy",
  "delve",
  "js-debug-adapter",
  "netcoredbg",
  -- linters
  "dotenv-linter",
  "hadolint",
  "markdownlint-cli2",
  "shellcheck",
  "snyk",
  "sqlfluff",
  "tflint",
  -- formatters
  "beautysh",
  "black",
  "gofumpt",
  "goimports",
  "markdown-toc",
  "markdownlint-cli2",
  "prettier",
  "prettierd",
  "shfmt",
  "stylua",
  "yamlfmt",
}
