return {
  diagnostics = {
    Error = "",
    Hint = "",
    Info = "",
    Warn = "",
  },
  documents = {
    File = "",
    Files = "",
    FolderClosed = "",
    FolderOpened = "",
  },
  git = {
    Branch = "",
    Commit = "",
    Compare = "",
    Merge = "",
    PullRequest = "",
  },
  kind = {
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "陋",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Keyword = "",
    Method = "",
    Module = "",
    Operator = "",
    Property = "",
    Reference = "",
    Snippet = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  misc = {
    Bug = "",
    Calendar = "",
    CaretRight = "",
    ChevronRight = "›",
    Clipboard = "",
    Dot = "▪",
    FilledCircle = "●",
    FoldClosed = "",
    FoldOpened = "",
    Layer = "﬘",
    Lock = "",
    Orbit = " ",
    Prompt = "❯",
    RightArrow = "",
    ScriptSmall = "ℓ",
    Table = "",
    Tag = "",
    VerticalBar = "▍",
    VerticalBarBold = "▊",
    VerticalBarSplit = "┊",
    VerticalBarThin = "│",
    Watch = "",
  },
  status = {
    Error = "",
    Warn = "",
  },
  type = {
    Array = "",
    Boolean = "",
    Number = "",
    Object = "",
    String = "",
  },
}
