return {
  diagnostics = {
    Error = "",
    Hint = "",
    Info = "",
    Warn = "",
  },
  debug = {
    Bug = "",
    Continue = "",
    Disconnect = "",
    Pause = "",
    Restart = "",
    Start = "",
    StepInto = "",
    StepOut = "",
    StepOver = "",
    StepBack = "",
    Stop = "",
    Breakpoints = "",
    REPL = "",
    Scopes = "",
    Stacks = "",
    Watches = "",
  },
  documents = {
    File = "",
    Files = "",
    FolderClosed = "",
    FolderOpened = "",
  },
  git = {
    Branch = "",
    Commit = "",
    Compare = "",
    Merge = "",
    PullRequest = "",
    TextAdded = "",
    TextChanged = "",
    TextRemoved = "",
  },
  groups = {
    Book = "",
    Lab = "",
  },
  kind = {
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "陋",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Keyword = "",
    Method = "",
    Module = "",
    Operator = "",
    Property = "",
    Reference = "",
    Snippet = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  misc = {
    Calendar = "",
    CaretRight = "",
    CheckFilled = "",
    ChevronRight = "›",
    Circle = "",
    Clipboard = "",
    Close = "",
    CloseBold = "",
    Dot = "▪",
    FilledCircle = "●",
    FoldClosed = "",
    FoldOpened = "",
    Key = "",
    Layer = "﬘",
    LeftArrow = "",
    LeftArrowCircled = "",
    Lock = "",
    Orbit = " ",
    Prompt = "❯",
    RightArrow = "",
    RightArrowCircled = "",
    ScriptSmall = "ℓ",
    Square = "■",
    Table = "",
    Tag = "",
    VerticalBar = "▍",
    VerticalBarBold = "▊",
    VerticalBarSplit = "┊",
    VerticalBarThin = "│",
    Watch = "",
  },
  status = {
    Error = "",
    Warn = "",
  },
  type = {
    Array = "",
    Boolean = "",
    Number = "",
    Object = "",
    String = "",
  },
}
