local M = {}

---@param c util.theme_palette
---@return util.theme_hl
M.get = function(c)
  local CYAN = "#73c1b9"
  local CYAN_LIGHT = "#80d3dd"
  local PINK = "#dec7d0"
  local ORANGE = "#e09696"
  local YELLOW = "#ffdca8"
  local MAGENTA = "#9086a4"
  local MAGENTA_LIGHT = "#bfafc4"
  -- stylua: ignore
  return {
    -- treesitter highlighting
    ["@annotation"]                   = { fg = c.yellow2 },
    ["@attribute"]                    = { fg = c.yellow2 },
    ["@boolean"]                      = { link = "Boolean" },
    ["@character"]                    = { link = "Character" },
    ["@character.special"]            = { link = "SpecialChar" },
    ["@class"]                        = { fg = c.cyan0, bold = true },
    ["@comment"]                      = { link = "Comment" },
    ["@comment.documentation"]        = { link = "SpecialComment" },
    ["@comment.error"]                = { link = "Error" },
    ["@comment.hint"]                 = { link = "DiagnosticHint" },
    ["@comment.info"]                 = { link = "DiagnosticInfo" },
    ["@comment.note"]                 = { link = "DiagnosticInfo" },
    ["@comment.todo"]                 = { link = "Todo" },
    ["@comment.warning"]              = { link = "WarningMsg" },
    ["@conceal"]                      = { link = "Conceal" },
    ["@constant"]                     = { link = "Constant" },
    ["@constant.builtin"]             = { bold = true },
    ["@constant.macro"]               = { fg = c.cyan0, italic = true },
    ["@constructor"]                  = { fg = c.aqua1 },
    ["@definition.enum"]              = { bold = true },
    ["@diff.delta"]                   = { link = "DiffChange" },
    ["@diff.minus"]                   = { link = "DiffDelete" },
    ["@diff.plus"]                    = { link = "DiffAdd" },
    ["@error"]                        = { fg = c.red1 },
    ["@function"]                     = { link = "Function" },
    ["@function.builtin"]             = { bold = true },
    ["@function.call"]                = { link = "Function" },
    ["@function.macro"]               = { fg = c.blue1 },
    ["@function.method"]              = { link = "Function" },
    ["@function.method.call"]         = { link = "Function" },
    ["@keyword"]                      = { link = "Keyword" },
    ["@keyword.coroutine"]            = { link = "@keyword" },
    ["@keyword.conditional"]          = { link = "Conditional" },
    ["@keyword.debug"]                = { link = "Debug" },
    ["@keyword.directive"]            = { link = "PreProc" },
    ["@keyword.directive.define"]     = { link = "Define" },
    ["@keyword.exception"]            = { link = "Exception" },
    ["@keyword.function"]             = { fg = c.magenta1 },
    ["@keyword.import"]               = { link = "Include" },
    ["@keyword.operator"]             = { fg = c.magenta1 },
    ["@keyword.repeat"]               = { link = "Repeat" },
    ["@keyword.return"]               = { fg = c.red2 },
    ["@keyword.storage"]              = { link = "StorageClass" },
    ["@label"]                        = { link = "Label" },
    ["@markup"]                       = {},
    ["@markup.danger"]                = { fg = c.bg2, bg = c.red1 },
    ["@markup.diff.add"]              = { link = "DiffAdd" },
    ["@markup.diff.delete"]           = { link = "DiffDelete" },
    ["@markup.emphasis"]              = { fg = c.yellow2, italic = true },
    ["@markup.environment"]           = { fg = c.blue4 },
    ["@markup.environment.name"]      = { fg = c.yellow2 },
    ["@markup.italic"]                = { italic = true },
    ["@markup.link"]                  = { fg = ds.color.lighten(c.overlay1, 30) },
    ["@markup.link.label"]            = { fg = c.purple1 },
    ["@markup.link.label.symbol"]     = { link = "Identifier" },
    ["@markup.link.url"]              = { underline = true },
    ["@markup.list"]                  = { fg = c.aqua0 },
    ["@markup.list.checked"]          = { fg = c.green2 },
    ["@markup.list.unchecked"]        = { fg = c.overlay1 },
    ["@markup.math"]                  = { fg = c.purple0 },
    ["@markup.note"]                  = { fg = c.bg2, bg = c.aqua0 },
    ["@markup.raw"]                   = { fg = ds.color.blend(c.rose0, c.bg2, 0.80) },
    ["@markup.raw.markdown_inline"]   = { bg = ds.color.blend(c.blue4, c.bg0, 0.08) },
    ["@markup.strikethrough"]         = { strikethrough = true },
    ["@markup.strong"]                = { bold = true },
    ["@markup.todo"]                  = { link = "Todo" },
    ["@markup.underline"]             = { link = "Underlined" },
    ["@markup.warning"]               = { fg = c.bg2, bg = c.yellow2 },
    ["@module"]                       = { fg = c.blue1 },
    ["@module.builtin"]               = { fg = c.blue1, bold = true },
    ["@namespace.builtin"]            = { link = "@variable.builtin" },
    ["@none"]                         = {},
    ["@number"]                       = { link = "Number" },
    ["@number.float"]                 = { link = "Float" },
    ["@operator"]                     = { link = "Operator" },
    ["@property"]                     = { fg = c.fg1 },
    ["@punctuation.bracket"]          = { fg = c.aqua0 },
    ["@punctuation.delimiter"]        = { fg = c.aqua0 },
    ["@punctuation.special"]          = { fg = c.purple0 },
    ["@string"]                       = { link = "String" },
    ["@string.documentation"]         = { link = "SpecialComment" },
    ["@string.escape"]                = { fg = c.purple0 },
    ["@string.regexp"]                = { fg = c.rose1 },
    ["@string.special"]               = { link = "SpecialChar" },
    ["@string.special.symbol"]        = { fg = c.blue1 },
    ["@structure"]                    = { link = "Structure" },
    ["@tag"]                          = { link = "tag" },
    ["@tag.attribute"]                = { fg = c.orange0 },
    ["@tag.delimiter"]                = { link = "Delimiter" },
    ["@type"]                         = { link = "Type" },
    ["@type.builtin"]                 = { bold = true },
    ["@type.definition"]              = { link = "TypeDef" },
    ["@type.qualifier"]               = { link = "Type" },
    ["@variable"]                     = { fg = c.fg1 },
    ["@variable.builtin"]             = { fg = c.fg2, bold = true },
    ["@variable.member"]              = { fg = c.fg1 },
    ["@variable.parameter"]           = { fg = c.rose0 },
    ["@variable.parameter.builtin"]   = { fg = c.rose0, bold = true },
    ["@variable.parameter.reference"] = { fg = c.rose0 },

    -- custom treesitter extended highlighting
    ["@markup.codeblock"]             = { link = "@markup.raw.markdown_inline"},
    ["@markup.dash"]                  = { fg = c.overlay0, bold = true },
    ["@markup.heading"]               = { link = "htmlH1" },
    ["@markup.heading.sub"]           = { link = "htmlH2" },
    ["@markup.table"]                 = { link = "@punctuation.special" },
    ["@variable.member.yaml"]         = { fg = c.aqua1 },

    -- nvim-treesitter-context
    TreesitterContext               = { link = "Normal" },
    TreesitterContextLineNumber     = { link = "LineNr" },
    TreesitterContextSeparator      = { link = "NonText" },

    -- rainbow-delimiters.nvim
    ["TSRainbow1"]                  = { fg = CYAN },
    ["TSRainbow2"]                  = { fg = ORANGE },
    ["TSRainbow3"]                  = { fg = MAGENTA },
    ["TSRainbow4"]                  = { fg = CYAN_LIGHT },
    ["TSRainbow5"]                  = { fg = PINK },
    ["TSRainbow6"]                  = { fg = MAGENTA_LIGHT },
    ["TSRainbow7"]                  = { fg = YELLOW }
  }
end

return M
