local telescope = require "remote.telescope"
local map = require("util").map

map.nnoremap("<localleader><localleader>", function()
  telescope.find_nvim()
end)
map.nnoremap("<leader><leader>", function()
  telescope.project_files()
end)
map.nnoremap("<leader>f/", function()
  telescope.grep_last_search()
end)
map.nnoremap("<leader>fb", function()
  telescope.buffers()
end)
map.nnoremap("<leader>fe", function()
  telescope.file_browser()
end)
map.nnoremap("<leader>ff", function()
  telescope.current_buffer()
end)
map.nnoremap("<leader>fg", function()
  telescope.live_grep()
end)
map.nnoremap("<leader>fgg", function()
  telescope.rg.live_grep_with_shortcuts()
end)
map.nnoremap("<leader>fk", function()
  telescope.help_tags()
end)

if vim.env.hash_notes then
  local md = require "custom.markdown"
  map.nnoremap("<leader>mm", function()
    md.create_note()
  end)
  map.nnoremap("<localleader>mm", function()
    telescope.find_files { cwd = vim.env.hash_notes }
  end)
  map.nnoremap("<leader>mr", function()
    md.create_template_reference()
  end)
end

map.nnoremap("<leader>fp", function()
  telescope.find_plugins()
end)
map.nnoremap("<leader>ws", function()
  telescope.lsp.workspace_symbols()
end)
