local M = {}

---@param c util.theme.palette
---@return util.theme.hl
function M.get(c)
  -- stylua: ignore
  return {
    -- treesitter highlighting
    ["@attribute"]                    = { link = "Constant" },
    ["@comment.documentation"]        = { link = "Comment" },
    ["@comment.error"]                = { fg = c.bg2, bg = c.red1 },
    ["@comment.hint"]                 = { fg = c.bg2, bg = c.blue1 },
    ["@comment.note"]                 = { fg = c.bg2, bg = c.rose1 },
    ["@comment.todo"]                 = { fg = c.bg2, bg = c.rose0 },
    ["@comment.warning"]              = { fg = c.bg2, bg = c.yellow1 },
    ["@constant.builtin"]             = { fg = c.orange0 },
    ["@constant.macro"]               = { link = "Macro" },
    ["@constructor"]                  = { fg = c.yellow1 },
    ["@error"]                        = { link = "Error" },
    ["@function.builtin"]             = { fg = c.orange0 },
    ["@function.macro"]               = { fg = c.magenta2 },
    ["@keyword.coroutine"]            = { link = "Keyword" },
    ["@keyword.debug"]                = { link = "Exception" },
    ["@keyword.function"]             = { fg = c.purple1 },
    ["@keyword.modifier"]             = { link = "Keyword" },
    ["@keyword.operator"]             = { fg = c.purple1 },
    ["@keyword.return"]               = { fg = c.purple1 },
    ["@keyword.type"]                 = { link = "Keyword" },
    ["@markup"]                       = { fg = c.fg2 },
    ["@markup.environment"]           = { fg = c.magenta2 },
    ["@markup.environment.name"]      = { fg = c.blue1 },
    ["@markup.heading"]               = { fg = c.blue1 },
    ["@markup.heading.markdown"]      = { bold = true },
    ["@markup.italic"]                = { fg = c.red1, italic = true },
    ["@markup.link"]                  = { fg = c.purple0 },
    ["@markup.link.label"]            = { fg = c.purple0 },
    ["@markup.link.url"]              = { fg = c.blue1, italic = true, underline = true },
    ["@markup.list"]                  = { fg = c.cyan1 },
    ["@markup.list.checked"]          = { fg = c.green1 },
    ["@markup.math"]                  = { fg = c.blue1 },
    ["@markup.quote"]                 = { fg = c.magenta2 },
    ["@markup.raw"]                   = { fg = c.green1 },
    ["@markup.strikethrough"]         = { fg = c.fg2, strikethrough = true },
    ["@markup.strong"]                = { fg = c.red1, bold = true },
    ["@module"]                       = { fg = c.yellow1, italic = true },
    ["@property"]                     = { fg = c.purple0 },
    ["@punctuation.bracket"]          = { fg = c.overlay2 },
    ["@punctuation.delimiter"]        = { link = "Delimiter" },
    ["@punctuation.special"]          = { link = "Special" },
    ["@string.documentation"]         = { fg = c.cyan1 },
    ["@string.escape"]                = { fg = c.magenta2 },
    ["@string.regexp"]                = { fg = c.magenta2 },
    ["@string.special"]               = { link = "Special" },
    ["@string.special.path"]          = { link = "Special" },
    ["@string.special.symbol"]        = { fg = c.rose0 },
    ["@string.special.url"]           = { fg = c.blue1, italic = true, underline = true },
    ["@tag"]                          = { fg = c.blue1 },
    ["@tag.attribute"]                = { fg = c.yellow1, italic = true },
    ["@tag.builtin"]                  = { fg = c.blue1 },
    ["@tag.delimiter"]                = { fg = c.cyan1 },
    ["@type.builtin"]                 = { fg = c.purple1, italic = true },
    ["@type.definition"]              = { link = "Type" },
    ["@variable"]                     = { fg = c.fg2 },
    ["@variable.builtin"]             = { fg = c.red1 },
    ["@variable.member"]              = { fg = c.purple0 },
    ["@variable.parameter"]           = { fg = c.red0 },

    -- language specific
    ["@attribute.c_sharp"]            = { fg = c.yellow1 },
    ["@character.special.html"]       = { fg = c.red1 },
    ["@comment.warning.gitcommit"]    = { fg = c.yellow1 },
    ["@constant.java"]                = { fg = c.cyan1 },
    ["@function.builtin.bash"]        = { fg = c.red1, italic = true },
    ["@function.method.php"]          = { link = "Function" },
    ["@function.method.call.php"]     = { link = "Function" },
    ["@keyword.export"]               = { fg = c.purple1 },
    ["@keyword.import.c"]             = { fg = c.yellow1 },
    ["@keyword.import.cpp"]           = { fg = c.yellow1 },
    ["@number.css"]                   = { fg = c.orange0 },
    ["@property.css"]                 = { fg = c.blue1 },
    ["@property.scss"]                = { fg = c.blue1 },
    ["@property.id.css"]              = { fg = c.yellow1 },
    ["@property.class.css"]           = { fg = c.yellow1 },
    ["@punctuation.delimiter.regex"]  = { link = "@string.regexp" },
    ["@string.plain.css"]             = { fg = c.fg2 },
    ["@string.special.path.gitignore"] = { fg = c.fg2 },
    ["@string.special.symbol.ruby"]   = { fg = c.rose0 },
    ["@string.special.url.html"]      = { fg = c.green1 },
    ["@type.css"]                     = { fg = c.purple0 },
    ["@type.tag.css"]                 = { fg = c.blue1 },
    ["@variable.parameter.bash"]      = { fg = c.green1 },

    -- custom treesitter extended highlighting
    ["@constructor.lua"]              = { link = "@punctuation.bracket" },
    ["@constructor.python"]           = { fg = c.aqua1 },
    ["@label.yaml"]                   = { fg = c.yellow1 },
    ["@markup.link.label.html"]       = { fg = c.fg2 },
    ["@markup.table"]                 = { link = "@punctuation.special" },
    ["@variable.member.yaml"]         = { fg = c.yellow1 },
  }
end

return M
