return { ---@class ft.defaults
  bash = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 2,
  },
  cs = {
    colorcolumn = "120",
    expandtab = true,
    shiftwidth = 4,
    softtabstop = 4,
    tabstop = 4,
  },
  css = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 2,
  },
  gitcommit = {
    colorcolumn = "50,72",
    foldenable = false,
    number = false,
    relativenumber = false,
    spell = true,
    swapfile = false,
    textwidth = 72,
    undofile = false,
    wrap = false,
  },
  go = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 4,
    softtabstop = 4,
    tabstop = 4,
  },
  html = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 2,
  },
  javascript = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 2,
  },
  javascriptreact = {
    colorcolumn = "120",
    expandtab = true,
    shiftwidth = 2,
  },
  json = {
    colorcolumn = "120",
    conceallevel = 0,
    expandtab = true,
    shiftwidth = 2,
  },
  json5 = {
    colorcolumn = "120",
    conceallevel = 0,
    expandtab = true,
    shiftwidth = 2,
  },
  jsonc = {
    colorcolumn = "120",
    conceallevel = 0,
    expandtab = true,
    shiftwidth = 2,
  },
  lua = {
    colorcolumn = "120",
    expandtab = true,
    include = [=[\v<((do|load)file|require)\s*\(?['"]\zs[^'"]+\ze['"]]=],
    includeexpr = [[v:lua.require("ft.lua").include_expr(v:fname)]],
    keywordprg = ":help",
    shiftwidth = 2,
  },
  markdown = {
    breakindent = true,
    breakindentopt = "min:5,list:-1",
    concealcursor = "n",
    conceallevel = 2,
    formatlistpat = [=[^\s*\d\+\.\s\+\|^\s*[-*+>]\s\+\|^\[^\ze[^\]]\+\]:]=],
    iskeyword = vim.opt.iskeyword:append "-",
    listchars = vim.opt.listchars:append "eol: ",
    spell = false,
    wrap = true,
  },
  ps1 = {
    colorcolumn = "120",
    expandtab = true,
    shiftwidth = 2,
  },
  python = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 4,
    softtabstop = 4,
    tabstop = 4,
  },
  rust = {
    colorcolumn = "100",
    expandtab = true,
    shiftwidth = 4,
    softtabstop = 4,
    tabstop = 4,
  },
  sh = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 2,
  },
  sql = {
    colorcolumn = "80",
    expandtab = true,
    relativenumber = false,
    shiftwidth = 4,
    softtabstop = 4,
    tabstop = 4,
  },
  typescript = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 2,
  },
  typescriptreact = {
    colorcolumn = "120",
    expandtab = true,
    shiftwidth = 2,
  },
  zsh = {
    colorcolumn = "80",
    expandtab = true,
    shiftwidth = 2,
  },
  ["vim"] = {
    colorcolumn = "120",
    expandtab = true,
    foldmethod = "marker",
    shiftwidth = 2,
  },
  -- misc
  checkhealth = {
    number = false,
    relativenumber = false,
  },
}
