[colors]
foreground = "#b4bac6"
background = "#373737"
cursor_bg = "#dfe3ec"
cursor_border = "#dfe3ec"
cursor_fg = "#373737"
selection_bg = "#48525e"
selection_fg = "#373737"

ansi = [
	"#59595e",
	"#bf616a",
	"#7f966d",
	"#d3b67d",
	"#6f8fb4",
	"#90718a",
	"#77b3c5",
	"#c9d1d9",
]
brights = [
	"#97979f",
	"#c97470",
	"#97b182",
	"#ddc380",
	"#81a1c1",
	"#b48ead",
	"#89b8c4",
	"#d8dee9",
]

[colors.tab_bar]
inactive_tab_edge = "#373737"
background = "#373737"

[colors.tab_bar.active_tab]
bg_color = "#373737"
fg_color = "#b8bec9"

[colors.tab_bar.inactive_tab]
bg_color = "#373737"
fg_color = "#59595e"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#373737"
fg_color = "#6f8fb4"

[colors.tab_bar.new_tab_hover]
bg_color = "#373737"
fg_color = "#6f8fb4"

[colors.tab_bar.new_tab]
bg_color = "#373737"
fg_color = "#6f8fb4"

[metadata]
name = "kdark"
